# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnyDoTest' do

  use_frameworks!
	pod 'Starscream', '~> 3.0.2'
	pod 'SwiftyJSON', '~> 4.0'


end
